[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-fps", "60", "--transition-pos", "0.854, 0.977", "--transition-step", "90"]   
set = true


#[templates.alacritty]
#input_path = '~/hyprflake/home/programs/matugen/templates/alacritty-colors.toml'
#output_path = '~/.config/alacritty/colors.toml'

#[templates.kitty]
#input_path = '~/hyprflake/home/programs/matugen/templates/kitty-colors.conf'
#output_path = '~/.config/kitty/colors.conf'
#post_hook = 'pkill -SIGUSR1 kitty'
# #post_hook = "kitty +kitten themes --reload-in=all custom"

[templates.hyprland]
input_path = '~/hyprflake/home/programs/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/hyprflake/home/programs/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/hyprflake/scripts/status_bar.sh'

[templates.cava]
input_path = '~/hyprflake/home/programs/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/custom'
post_hook = "pkill -USR1 cava"

[templates.wlogout]
input_path = '~/hyprflake/home/programs/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.starship]
input_path = '~/hyprflake/home/programs/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.dunst]
input_path = '~/hyprflake/home/programs/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc_mutable'
post_hook = 'cat ~/.config/dunst/dunstrc ~/.config/dunst/dunstrc_mutable > ~/.config/dunst/dunstrc_combined && mv ~/.config/dunst/dunstrc_combined ~/.config/dunst/dunstrc_mutable && dunstctl reload ~/.config/dunst/dunstrc_mutable'

[templates.pywalfox]
input_path = '~/hyprflake/home/programs/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.firefox-usercontent]
input_path = '~/hyprflake/home/programs/matugen/templates/userContent.css'
output_path = '~/.mozilla/firefox/default/chrome/userContent.css'

[templates.btop]
input_path = '~/hyprflake/home/programs/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'